#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     ,               sensorLightActive)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    tip,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void lineUp()
{
	int speedNow = 20;
	while(SensorValue(IR) < 5)
	{
		motor[motorD] = -speedNow;
		motor[motorE] = -speedNow;
		wait1Msec(5);
		return;
	}

	while(SensorValue(IR) > 5)
	{
		motor[motorD] = speedNow;
		motor[motorE] = speedNow;
		wait1Msec(5);
		return;
	}

	while(SensorValue(IR) == 5)
	{
		return;
	}
}

//void updateIR()
//{
//	while(SensorValue(IR) != 5)
//	{
//		motor[motorA] = 50;
//	}
//}

task main()
{
		waitForStart();

		while(true)
		{
			lineUp();
		}
}
