#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          IRThing,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_2,    tip,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C3_1,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";


void stopAll()
{
	//Sets all motors to zero, stops robot
	motor[motorD] = 0;
	motor[motorE] = 0;
}

void update()
{
	getJoystickSettings(joystick);
}

task main()
{
	while(true)
	{
		update();

		// Calls the stopAll() method to stop motors
		if(joy1Btn(2) == 1)
			stopAll();

		else if(joy1Btn(7) == 1)
				motor[motorD] = 0;
		else if(joy1Btn(8) == 1)
				motor[motorE] = 0;

		// If trigger is pressed, speed up robot
		update();
		if(joy1Btn(5) == 1)
		{
			if (joystick.joy1_y1 < -25 || joystick.joy1_y1 > 25)
			{
				motor[motorD] = joystick.joy1_y1/4;
			}

			else
			{
				motor[motorD] = 0;
			}

			if (joystick.joy1_y2 < -25 || joystick.joy1_y2 > 25)
			{
				motor[motorE] = -joystick.joy1_y2/4;
			}

			else
			{
				motor[motorE] = 0;
			}
		}

		update();
		if(!joy1Btn(5) == 1)
		{
			if (joystick.joy1_y1 < -25 || joystick.joy1_y1 > 25)
			{
				motor[motorD] = -joystick.joy1_y1;
			}

			else
			{
				motor[motorD] = 0;
			}

			if (joystick.joy1_y2 < -25 || joystick.joy1_y2 > 25)
			{
				motor[motorE] = -joystick.joy1_y2;
			}

			else
			{
				motor[motorE] = 0;
			}
		}

		if(joystick.joy2_y1 < 25 || joystick.joy2_y1 > 25)
		{
			motor[motorF] = joystick.joy2_y1 / 10;
		}

		if(joystick.joy2_y2 < 25 || joystick.joy2_y2 > 25)
		{
			motor[motorG] = joystick.joy2_y2;
		}

		while(joy2Btn(0) == 1)
		{
			servo[tip] = ServoValue[tip] + 10;
			update();
		}

		while(joy2Btn(1) == 1)
		{
			servo[tip] = ServoValue[tip] - 10;
			update();
		}
	}
}
