#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

void stopAll()
{
	//Sets all motors to zero, stops robot
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
}

task main()
{

	while(true)
	{
		getJoystickSettings(joystick);

		// Calls the stopAll() method to stop motors
		if(joy1Btn(1) == 1)
			stopAll();

		// If trigger is pressed, slow down robot
		if(joy1Btn(7) == 1)
		{
			motor[motorD] = joystick.joy1_y1 / 2;
			motor[motorE] = joystick.joy1_y1 / 2;
			motor[motorF] = joystick.joy1_y2 / 2;
			motor[motorG] = joystick.joy1_y2 / 2;
		}

		// When nothing is pressed, normal speed
		else
		{
			motor[motorD] = joystick.joy1_y1;
			motor[motorE] = joystick.joy1_y1;
			motor[motorF] = joystick.joy1_y2;
			motor[motorG] = joystick.joy1_y2;
		}
	}
}
