#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    tip,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////////////////////////////////////////////////////////////////////
//
//	noIRAuto (Team 6150's autonomous without the IR beacon)
//
//	This file contains the code neccesary for the robot to run one of our multiple
//	autonomous files. This specific program is designed so that our alliance team has
//	an opportunity to score in the IR beacon. We made this program so that we could
// 	avoid a collision that would impair both robots.
//
//	This program drops a block into the nearest goal, then drives onto the ramp. It needs
//	to be set up directly in front of the nearest basket in order to work. This is a
//	quick and simple program is guaranteed to be crash-free with our alliance member team.
//
//	Last modified - Dec 31st, 2013
//	@author - Manu S.
//
//////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"

task main()
{
	waitForStart();

	// Go forward to the basket
	motor[motorD] = 50;
	motor[motorE] = 50;
	wait1Msec(100);

	// Drop the block into the basket
	motor[motorF] = 20;
	wait1Msec(1000);

	// Back away from the basket
	motor[motorD] = -50;
	motor[motorE] = -50;
	wait1Msec(90); // not a complete backup
	// because we don't want to go to the wall

	// Turn 90 degrees
	motor[motorD] = -50;
	motor[motorE] = 50;
	wait1Msec(1000);

	// Go forward a little
	motor[motorD] = 50;
	motor[motorE] = 50;
	wait1Msec(2500);

	// Turn to look at the ramp
	motor[motorD] = 50;
	motor[motorE] = -50;
	wait1Msec(1000);

	// Drive up to score!
	motor[motorD] = 50;
	motor[motorE] = 50;
	wait1Msec(2100);

}
