#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S2_C1_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";


void stopAll()
{
	//Sets all motors to zero, stops robot
	motor[motorD] = 0;
	motor[motorE] = 0;
}

task main()
{

	while(true)
	{
		getJoystickSettings(joystick);

		// Calls the stopAll() method to stop motors
		if(joy1Btn(2) == 1)
			stopAll();

		// If trigger is pressed, speed up robot
		if(joy1Btn(8) == 1)
		{
			getJoystickSettings(joystick);
			if (joystick.joy1_x2 < -100 || joystick.joy1_x2 > 100)
			{
					motor[motorD] = joystick.joy1_x2;
					motor[motorE] = -joystick.joy1_x2;
			}
			getJoystickSettings(joystick);
			if (joystick.joy1_y1 < -100 || joystick.joy1_y1 > 100)
			{
				motor[motorD] = -joystick.joy1_y1;
				motor[motorE] = -joystick.joy1_y1;
			}
		}

		else
		{
			getJoystickSettings(joystick);
			if (joystick.joy1_x2 > -100 || joystick.joy1_x2 < 100)
			{
					motor[motorD] = joystick.joy1_x2/2;
					motor[motorE] = -joystick.joy1_x2/2;
			}
			getJoystickSettings(joystick);
			if (joystick.joy1_y1 < -100 || joystick.joy1_y1 > 100)
			{
				motor[motorD] = -joystick.joy1_y1/2;
				motor[motorE] = -joystick.joy1_y1/2;
			}
		}
	}
}
