#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorLightActive)
#pragma config(Sensor, S4,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    tip,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

void stopAll()
{
	//Sets all motors to zero, stops robot
	motor[motorD] = 0;
	motor[motorE] = 0;
}

task main()
{
	//bool x = true;
	while(true)
	{
		getJoystickSettings(joystick);

		while(true)
		{

			// Calls the stopAll() method to stop motors
			if(joy1Btn(2) == 1)
				stopAll();

			// If trigger is pressed, speed up robot
			if(joy1Btn(8) == 1)
			{
			//	getJoystickSettings(joystick);
				if (-10 > joystick.joy1_x2 > -100 || 10 < joystick.joy1_x2 < 100)
				{
						motor[motorD] = -joystick.joy1_x2;
						motor[motorE] = joystick.joy1_x2; // reversed them back
				}
			//	getJoystickSettings(joystick);
				if ( -10 > joystick.joy1_y1 > -100 || 10 < joystick.joy1_y1 < 100)
				{
					motor[motorD] = joystick.joy1_y1;
					motor[motorE] = joystick.joy1_y1;
				}
				//getJoystickSettings(joystick);
				if (-10 > joystick.joy2_y1 > 100 || 10 < joystick.joy2_y1 < 100)
				{
					motor[motorF] = joystick.joy2_y1/4;
				}
				//getJoystickSettings(joystick);
				if (-10 > joystick.joy2_y2 > -100 || 10< joystick.joy2_y2 < 100)
				{
					motor[motorG] = joystick.joy2_y2/4;
				}
			}

			else
			{
				//getJoystickSettings(joystick);
				if (-10 > joystick.joy1_x2 > -100 || 10 < joystick.joy1_x2 < 100)
				{
						motor[motorD] = -joystick.joy1_x2/2;
						motor[motorE] = joystick.joy1_x2/2;
				}
				//getJoystickSettings(joystick);
				if (-10 > joystick.joy1_y1 > -100 || 10 < joystick.joy1_y1 < 100)
				{
					motor[motorD] = joystick.joy1_y1/2;
					motor[motorE] = joystick.joy1_y1/2;
				}
				//getJoystickSettings(joystick);
				if (-10 > joystick.joy2_y1 > 100 || 10 < joystick.joy2_y1 < 100)
				{
					motor[motorF] = joystick.joy2_y1/4;
				}
				//getJoystickSettings(joystick);
				if (-10 > joystick.joy2_y2 > -100 || 10< joystick.joy2_y2 < 100)
				{
					motor[motorG] = joystick.joy2_y2/4;
				}
				while(joy2Btn(7) == 1)
					servo[tip] = ServoValue[tip] + 3;
				while(joy2Btn(8) == 1)
					servo[tip] = ServoValue[tip] - 3;
			}
		}

	//	while(!x)
	//	{
	//		getJoystickSettings(joystick);

	//		// Calls the stopAll() method to stop motors
	//		if(joy1Btn(2) == 1)
	//			stopAll();

	//		// If trigger is pressed, speed up robot
	//		while(joy1Btn(8) == 1)
	//		{
	//			getJoystickSettings(joystick);
	//			if ( -10 > joystick.joy1_y1 > -100 || 10 < joystick.joy1_y1 < 100)
	//			{
	//				motor[motorD] = -joystick.joy1_y1;
	//			}
	//			getJoystickSettings(joystick);
	//			if ( -10 > joystick.joy1_y1 > -100 || 10 < joystick.joy1_y1 < 100)
	//			{
	//				motor[motorE] = -joystick.joy1_y2;
	//			}
	//			getJoystickSettings(joystick);
	//			if (-10 > joystick.joy2_y1 > 100 || 10 < joystick.joy2_y1 < 100)
	//			{
	//				motor[motorF] = joystick.joy2_y1/4;
	//			}
	//			getJoystickSettings(joystick);
	//			if (-10 > joystick.joy2_y2 > -100 || 10< joystick.joy2_y2 < 100)
	//			{
	//				motor[motorG] = joystick.joy2_y2/4;
	//			}
	//		}

	//		while(joy1Btn(8) == 0)
	//		{
	//			getJoystickSettings(joystick);
	//			if (-10 > joystick.joy1_y1 > -100 || 10 < joystick.joy1_y1 < 100)
	//			{
	//				motor[motorD] = -joystick.joy1_y1/2;

	//			}
	//				getJoystickSettings(joystick);
	//			if (-10 > joystick.joy1_y1 > -100 || 10 < joystick.joy1_y1 < 100)
	//			{
	//				motor[motorE] = -joystick.joy1_y2/2;

	//			}
	//			getJoystickSettings(joystick);
	//			if (-10 > joystick.joy2_y1 > 100 || 10 < joystick.joy2_y1 < 100)
	//			{
	//				motor[motorF] = joystick.joy2_y1/4;
	//			}
	//			getJoystickSettings(joystick);
	//			if (-10 > joystick.joy2_y2 > -100 || 10< joystick.joy2_y2 < 100)
	//			{
	//				motor[motorG] = joystick.joy2_y2/4;
	//			}
	//			while(joy2Btn(7) == 1)
	//				servo[tip] = ServoValue[tip] + 3;
	//			while(joy2Btn(8) == 1)
	//				servo[tip] = ServoValue[tip] - 3;
	//		}
	//	}
	//	if(joy1Btn(1) == 1)
	//	{
	//		if(x==true)
	//		{
	//			x = false;
	//		}
	//		if(x==false)
	//		{
	//			x = true;
	//		}
	//}
		}
}
