#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     TrayUp,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    left,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    right,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    tip,                  tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

void closeClaw()
{
	servo[left] = 0;
	servo[right] = 0;
}

void openClaw()
{
	servo[left] = 255;
	servo[right] = 255;
}


void blocksUp()
{
	motor[TrayUp] = 10;
	wait10Msec(100);
}

void blocksDown()
{
	motor[TrayUp]= -10;
	wait10Msec(100);
}


void toDefault()
{
		openClaw();
		servo[tip] = 0;
}

task main()
{
		getJoystickSettings(joystick);

		if(joystick.joy2_TopHat == 0)
		{
			motor[TrayUp] = 0;
		}

		else
		{
			if(joy2Btn(3) == 1)
				closeClaw();

			else if(joy2Btn(1) == 1)
				openClaw();

			else{ 	}


			if(joy2Btn(4) == 1)
				blocksUp();

			else if(joy2Btn(2) == 1)
				blocksDown();

			else{  }


			if(joy2Btn(7) == 1)
				servo[tip] = -50;

			else if(joy2Btn(8) == 1)
				servo[tip] = 255;

			else{  }
		}
}
